import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {randomUUID,randomBytes} from 'node:crypto';
import {setup,body,type Harness} from './helpers.js';import {ids} from '../fixtures/synthetic/ids.js';import {DomainError} from '../packages/core/src/errors.js';
let h:Harness;before(async()=>{h=await setup();});after(async()=>{await h?.close();});
const reject=(p:Promise<unknown>,code:string)=>assert.rejects(p,e=>e instanceof DomainError&&e.code===code);
async function proposal(suffix:string){return h.knowledge.propose(h.users.alice,{project_id:ids.alpha,body:body(suffix),idempotency_key:randomUUID()});}
async function published(suffix:string){const p=await proposal(suffix),d=await h.reviewer.proposal(h.users.bob,p.proposal_id);return h.reviewer.decide(h.users.bob,{proposal_id:d.id,revision:d.current_revision,content_hash:d.content_hash,target_team_id:null,base_revision:null,decision:'accept',checks:{accuracy:true,applicability:true,evidence:true,no_secrets:true,audience:true},reason:'Synthetic follow-up test evidence checked.',valid_days:30,idempotency_key:randomUUID()});}
test('Only the author can withdraw a pending exact proposal revision',async()=>{const p=await proposal('withdraw');const input={proposal_id:p.proposal_id,revision:1,idempotency_key:randomUUID()};await reject(h.reviewer.withdraw(h.users.bob,input),'NOT_AVAILABLE');assert.equal((await h.reviewer.withdraw(h.users.alice,input)).status,'withdrawn');assert.equal((await h.reviewer.withdraw(h.users.alice,input)).status,'withdrawn');});
test('Feedback review inbox is restricted to authorized curators, not the membership administrator',async()=>{const p=await published('feedback-inbox');await h.knowledge.feedback(h.users.alice,{learning_id:p.learning_id,revision:1,category:'outdated',note:'Synthetic version needs review.',idempotency_key:randomUUID()});assert.ok((await h.reviewer.feedbackInbox(h.users.bob)).some(r=>r.learning_id===p.learning_id));assert.equal((await h.reviewer.feedbackInbox(h.users.admin)).length,0);assert.equal((await h.reviewer.feedbackInbox(h.users.charlie)).length,0);});
test('C09: a secret in a proposed team derivation is rejected before persistence',async()=>{const p=await published('derive-secret');const token='ghp_'+randomBytes(30).toString('hex').slice(0,36);await reject(h.reviewer.derive(h.users.bob,{source_learning_id:p.learning_id,source_revision:1,target_team_id:ids.team,body:{...body('forbidden-derived'),observation:`Synthetic secret canary ${token}`},sharing_confirmed:true,idempotency_key:randomUUID()}),'CONTENT_REJECTED');assert.equal((await h.owner.query('SELECT count(*)::int AS n FROM elm.proposal_revisions WHERE body::text LIKE $1',[`%${token}%`])).rows[0].n,0);});
test('D01: a successful empty search is not a dependency outage',async()=>{assert.equal((await h.knowledge.search(h.users.alice,{project_id:ids.alpha,query:'nonexistent-super-unique-marker'})).matches.length,0);await h.owner.query('UPDATE elm.service_state SET serving=false WHERE organization_id=$1',[ids.org]);try{await reject(h.knowledge.search(h.users.alice,{project_id:ids.alpha,query:'nonexistent-super-unique-marker'}),'DEPENDENCY_UNAVAILABLE');}finally{await h.owner.query('UPDATE elm.service_state SET serving=true WHERE organization_id=$1',[ids.org]);}});
test('Context catalog declares truncation without truncating any returned project',async()=>{for(let i=0;i<23;i++){const id=randomUUID();await h.owner.query('INSERT INTO elm.projects(id,organization_id,name) VALUES($1,$2,$3)',[id,ids.org,`Synthetic additional ${i}`]);await h.owner.query("INSERT INTO elm.project_memberships VALUES($1,$2,'reader')",[ids.alice,id]);}const ctx=await h.knowledge.context(h.users.alice,{});assert.equal(ctx.projects.length,20);assert.equal(ctx.truncated,true);assert.equal(ctx.limit,20);assert.equal((await h.knowledge.context(h.users.alice,{project_id:ids.alpha})).truncated,false);});
