// Synthetic domain/DB benchmark. Not a full HTTP, OAuth, native-client or company pilot.
import {setup,body} from '../tests/helpers.js';
import {randomUUID} from 'node:crypto';import {hash} from '../packages/core/src/canonical.js';import {ids} from '../fixtures/synthetic/ids.js';import {cpus,totalmem} from 'node:os';import {writeFile,mkdir} from 'node:fs/promises';
const h=await setup();try{
 const data=body('load-corpus'),contentHash=hash(data);
 await h.owner.query(`WITH inserted AS (INSERT INTO elm.learnings(id,organization_id,audience_kind,audience_id,current_revision,state,valid_until,review_due_at) SELECT gen_random_uuid(),$1,'project',$2,1,'active',now()+interval '30 days',now()+interval '30 days' FROM generate_series(1,10000) RETURNING id) INSERT INTO elm.learning_revisions(learning_id,revision,organization_id,body,content_hash,evidence_quality) SELECT id,1,$1,$3,$4,'reviewer_checked' FROM inserted`,[ids.org,ids.alpha,data,contentHash]);
 const users=[];for(let n=0;n<10;n++){const id=randomUUID();await h.owner.query('INSERT INTO elm.principals(id,organization_id,issuer,subject,display_name) VALUES($1::uuid,$2,$3,$1::text,$4)',[id,ids.org,h.config.issuer,`Synthetic load reader ${n}`]);await h.owner.query("INSERT INTO elm.project_memberships VALUES($1,$2,'reader')",[id,ids.alpha]);users.push(await h.mcp.identity({issuer:h.config.issuer,subject:id,scopes:['knowledge:read']}));}
 await h.owner.query('ANALYZE elm.learnings; ANALYZE elm.learning_revisions');
 const samples:number[]=[],failures:string[]=[];const started=performance.now(),pending=[];const requests=Number(process.env.ELM_LOAD_REQUESTS??200),rps=Number(process.env.ELM_LOAD_RPS??10);if(!Number.isInteger(requests)||requests<1||requests>1000||!Number.isFinite(rps)||rps<0.1||rps>20)throw new Error('Invalid bounded load profile');
 for(let i=0;i<requests;i++){await new Promise(r=>setTimeout(r,Math.max(0,started+i*(1000/rps)-performance.now())));pending.push((async()=>{const start=performance.now();try{const result=await h.knowledge.search(users[i%users.length]!,{project_id:ids.alpha,query:i%2?'Zeitüberschreitung':'retry timeout',limit:5});if(result.matches.length!==5)throw new Error('Unexpected match count');samples.push(performance.now()-start);}catch(e){failures.push(e&&typeof e==='object'&&'code' in e?String(e.code):'error');}})());}
 await Promise.all(pending);samples.sort((a,b)=>a-b);
 const report={scope:'synthetic domain service + real PostgreSQL + real secret scanner; excludes HTTP/OAuth/IDE',node:process.version,postgres:(await h.owner.query('SHOW server_version')).rows[0].server_version,cpu:cpus()[0]?.model,logical_cpus:cpus().length,memory_gib:Math.round(totalmem()/1024**3),corpus:10000,users:users.length,target_rps:rps,requests,successes:samples.length,errors:failures.length,error_codes:Object.fromEntries([...new Set(failures)].map(c=>[c,failures.filter(v=>v===c).length])),elapsed_ms:Math.round(performance.now()-started),p50_ms:Math.round(samples[Math.floor(samples.length*.50)]??0),p95_ms:Math.round(samples[Math.floor(samples.length*.95)]??0),p99_ms:Math.round(samples[Math.floor(samples.length*.99)]??0)};
 await mkdir('artifacts',{recursive:true});await writeFile('artifacts/loadtest.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(failures.length||report.p95_ms>=1000)process.exitCode=1;
}finally{await h.close();}
