import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import formbody from '@fastify/formbody';
import {readFile} from 'node:fs/promises';
import {type Config,checkHttpBoundary} from '../../../packages/core/src/config.js';
import {Database} from '../../../packages/core/src/database.js';
import {ReviewService} from '../../../packages/core/src/review.js';
import {KnowledgeService} from '../../../packages/core/src/knowledge.js';
import {POLICY_VERSION} from '../../../packages/core/src/contracts.js';
import {fail,DomainError,safeError,httpStatus} from '../../../packages/core/src/errors.js';
import {harden} from '../../../packages/core/src/http.js';
import {ReviewAuth} from './auth.js';
import {esc,page,hidden,bodyView,jsonForm,newKey} from './views.js';
export async function createReviewApp(config:Config,db:Database,review:ReviewService,knowledge:KnowledgeService){
 const app=Fastify({logger:false,bodyLimit:64*1024,requestTimeout:15000,connectionTimeout:15000,trustProxy:false});await app.register(cookie);await app.register(formbody);harden(app,false);const auth=await ReviewAuth.create(config,db);
 app.addHook('onRequest',async req=>{checkHttpBoundary(req.headers,config,req.method==='POST');if(req.headers.authorization!==undefined)fail('FORBIDDEN');});
 app.setErrorHandler((e,_req,reply)=>{const error=safeError(e);return reply.code(httpStatus(e)).type('text/html').send(page(error.code,`<p class="notice">The operation was not completed. No protected content is shown. ${esc(error.field)}</p><p><a href="/">Back to review inbox</a></p>`));});
 app.get('/styles.css',async(_req,reply)=>reply.type('text/css').send(await readFile('apps/review/src/styles.css','utf8')));
 app.get('/healthz',async(_req,reply)=>{try{await db.pool.query('SELECT 1');return {status:'alive'};}catch{return reply.code(503).send({status:'unavailable'});}});
 app.get('/auth/login',async(req,reply)=>auth.login(req,reply));app.get('/auth/callback',async(req,reply)=>auth.callback(req,reply));
 app.get('/',async(req,reply)=>{let session;try{session=await auth.authenticate(req);}catch(e){if(e instanceof DomainError&&e.code==='UNAUTHENTICATED')return reply.type('text/html').send(page('Experience worth sharing',`<p>Find reviewed engineering lessons. Keep new observations private until a colleague has checked them.</p><p class="notice">Individual OIDC accounts protect access. Only submit data approved for this deployment.</p><a class="tag" href="/auth/login">Sign in securely</a>`));throw e;}
  const rows=await review.inbox(session.principal);return reply.type('text/html').send(page('Review inbox',`<p class="muted">Only your own proposals and proposals you are allowed to review are shown.</p>${rows.length?rows.map(r=>`<div class="card"><div><a href="/proposals/${esc(r.id)}">${esc(r.title)}</a><p class="muted">Revision ${r.current_revision} · ${r.own?'Your proposal':'Peer review'}${r.target_team_id?' · Sanitized team derivation':''}</p></div><span class="tag">${esc(r.status)}</span></div>`).join(''):'<div class="panel">No proposals yet. Connect a coding client, select your project and enable participation.</div>'}`,session.principal.display_name,session.csrf));
 });
 app.get<{Params:{id:string}}>('/proposals/:id',async(req,reply)=>{const s=await auth.authenticate(req),r=await review.proposal(s.principal,req.params.id);let forms='';
  if(r.can_review&&r.status==='pending_review')forms+=`<form class="panel" method="post" action="/decide">${hidden('csrf',s.csrf)}${hidden('proposal_id',r.id)}${hidden('revision',r.current_revision)}${hidden('content_hash',r.content_hash)}${hidden('target_team_id',r.target_team_id??'')}${hidden('base_revision',r.base_revision??'')}${hidden('idempotency_key',newKey())}<h2>Review this exact revision</h2><p class="muted">Check the references yourself. The server has not verified them. Hash: ${esc(r.content_hash)}</p>${['accuracy','applicability','evidence','no_secrets','audience'].map(c=>`<label><input type="checkbox" name="${c}" value="yes"> I checked ${esc(c.replaceAll('_',' '))}.</label>`).join('')}<label>Reason<input name="reason" required maxlength="500"></label><div class="row"><label>Decision<select name="decision"><option value="accept">Publish this revision</option><option value="request_changes">Request changes</option><option value="reject">Reject</option></select></label><label>Valid for days<input name="valid_days" type="number" value="90" min="1" max="90"></label></div><button>Record review decision</button></form>`;
  if(r.own&&['pending_review','changes_requested'].includes(r.status))forms+=`<details><summary>Revise proposal</summary>${jsonForm('/revise',s.csrf,{proposal_id:r.id,revision:r.current_revision,content_hash:r.content_hash,body:r.body,idempotency_key:newKey()},'Save a new proposal revision')}</details>`;
  if(r.own&&['pending_review','changes_requested'].includes(r.status))forms+=jsonForm('/withdraw',s.csrf,{proposal_id:r.id,revision:r.current_revision,idempotency_key:newKey()},'Withdraw my proposal');
  return reply.type('text/html').send(page('Proposal review',`<p class="notice">${esc(r.status)} · Revision ${r.current_revision} · ${r.target_team_id?'TEAM audience: sanitized derivation requires peer review':'PROJECT audience'}${r.own?' · You cannot review your own proposal.':''}</p>${bodyView(r.body)}${r.base?`<details><summary>Compare previous published content</summary><pre>${esc(JSON.stringify(r.base,null,2))}</pre></details>`:''}${forms}`,s.principal.display_name,s.csrf));
 });
 app.get('/search',async(req,reply)=>{const s=await auth.authenticate(req),ctx=await knowledge.context(s.principal,{});const q=req.query as {project_id?:string;query?:string};let results='';if(q.project_id&&q.query){const found=await knowledge.search(s.principal,{project_id:q.project_id,query:q.query});results=found.matches.map(m=>`<div class="card"><a href="/learnings/${esc(m.learning_id)}">${esc(m.title)}</a><span class="tag">Revision ${esc(m.revision)}</span></div>`).join('')||'<p class="notice">No matching current guidance.</p>';}
 return reply.type('text/html').send(page('Reviewed knowledge',`<form class="panel" method="get" action="/search"><label>Project<select name="project_id">${ctx.projects.map(p=>`<option value="${p.project_id}">${esc(p.name)}</option>`).join('')}</select></label><label>Search terms — no secrets<input name="query" required maxlength="1024" value="${esc(q.query??'')}"></label><button>Find relevant lessons</button></form>${results}`,s.principal.display_name,s.csrf));});
 app.get<{Params:{id:string}}>('/learnings/:id',async(req,reply)=>{const s=await auth.authenticate(req),r=await knowledge.get(s.principal,{learning_id:req.params.id});const permitted=await db.transaction(s.principal,async tx=>(await tx.query('SELECT elm.curate_learning($1) AS ok',[r.learning_id])).rows[0]?.ok===true);let controls='';if(permitted){controls+=`<details><summary>Record a conflict with another visible learning</summary>${jsonForm('/conflicts',s.csrf,{left_id:r.learning_id,right_id:'REPLACE_WITH_OTHER_LEARNING_UUID',idempotency_key:newKey()},'Record reviewed conflict')}</details>`;controls+=`<details><summary>Suspend, revoke or archive</summary>${jsonForm('/retire',s.csrf,{learning_id:r.learning_id,revision:r.revision,state:'suspended',reason:'Requires a fresh accuracy review.',security_related:false,idempotency_key:newKey()},'Change availability')}</details>`;if(r.audience.kind==='project')controls+=`<details><summary>Create a sanitized team derivation</summary><p class="notice">Replace all restricted details and evidence. This creates a new proposal, never changes the source visibility. Another curator must review it.</p>${jsonForm('/derive',s.csrf,{source_learning_id:r.learning_id,source_revision:r.revision,target_team_id:'REPLACE_WITH_AUTHORIZED_TEAM_UUID',body:r.body,sharing_confirmed:false,idempotency_key:newKey()},'Submit sanitized derivation')}</details>`;}
 return reply.type('text/html').send(page('Published lesson',`<p class="notice">Revision ${r.revision} · Valid until ${esc(r.valid_until)} · ${esc(r.evidence_quality)}</p>${bodyView(r.body)}${r.conflicts_with.length?`<p class="notice">Known conflicting guidance: ${r.conflicts_with.map(id=>`<a href="/learnings/${esc(id)}">${esc(id)}</a>`).join(' ')}</p>`:''}${controls}`,s.principal.display_name,s.csrf));});
 app.get('/feedback',async(req,reply)=>{const s=await auth.authenticate(req),rows=await review.feedbackInbox(s.principal);return reply.type('text/html').send(page('Feedback requiring review',`<p class="muted">Security reports appear first. Feedback does not automatically change availability.</p>${rows.map(r=>`<section class="panel"><span class="tag">${esc(r.category)}</span><p>${esc(r.note??'No additional note')}</p><a href="/learnings/${esc(r.learning_id)}">${esc(r.learning_id)} · revision ${esc(r.revision)}</a></section>`).join('')||'<p>No feedback in your review scope.</p>'}`,s.principal.display_name,s.csrf));});
 app.get('/participation',async(req,reply)=>{const s=await auth.authenticate(req),ctx=await knowledge.context(s.principal,{});return reply.type('text/html').send(page('Participation',`<div class="notice">Only submit small, sanitized observations. No full chats, source files, customer or personal data. Suggestions stay unpublished until peer review. Guidance retrieved by a coding tool may be sent to its configured model provider.</div>${ctx.projects.filter(p=>p.role!=='reader').map(p=>`<form class="panel" method="post" action="/participation">${hidden('csrf',s.csrf)}${hidden('project_id',p.project_id)}${hidden('policy_version',POLICY_VERSION)}<h2>${esc(p.name)}</h2><p>Current mode: ${esc(p.participation_mode)}</p><label>Submission mode<select name="mode"><option value="manual">Manual: confirm each submission in the coding client</option><option value="auto">Auto-propose: allow qualified suggestions at task completion</option><option value="off">Off: disable submissions</option></select></label><p class="muted">Policy ${POLICY_VERSION}. The server cannot attest to clicks inside an IDE. Publishing is always a separate human review.</p><button>Save participation choice</button></form>`).join('')}`,s.principal.display_name,s.csrf));});
 app.get('/admin',async(req,reply)=>{const s=await auth.authenticate(req),data=await review.registry(s.principal);return reply.type('text/html').send(page('Registry administration',`<p class="notice">Registry administration grants no automatic access to project content. SCM permissions are not synchronized.</p><pre>${esc(JSON.stringify(data,null,2))}</pre>${jsonForm('/admin',s.csrf,{action:'create_project',name:'New project',team_id:null},'Apply registry change')}<details><summary>Supported registry actions</summary><pre>create_principal: name, subject\ncreate_team: name\ncreate_project: name, team_id\nset_active: id, active\nproject_membership / team_membership: id, principal_id, role (reader/contributor/curator/remove)\nrepository_alias: project_id, host, path</pre></details>`,s.principal.display_name,s.csrf));});
 app.post('/logout',async(req,reply)=>{const s=await auth.authenticate(req);auth.csrf(s.csrf,(req.body as Record<string,unknown>)?.csrf);await auth.logout(s.sessionHash,reply);});
 for(const route of ['decide','revise','retire','derive','participation','admin','conflicts','withdraw'] as const)app.post(`/${route}`,async(req,reply)=>{
  const s=await auth.authenticate(req),form=req.body as Record<string,unknown>;auth.csrf(s.csrf,form?.csrf);let input:unknown;
  if(route==='decide'){input={proposal_id:form.proposal_id,revision:Number(form.revision),content_hash:form.content_hash,target_team_id:form.target_team_id||null,base_revision:form.base_revision?Number(form.base_revision):null,decision:form.decision,checks:Object.fromEntries(['accuracy','applicability','evidence','no_secrets','audience'].map(c=>[c,form[c]==='yes'])),reason:form.reason,valid_days:Number(form.valid_days),idempotency_key:form.idempotency_key};}
  else if(route==='participation')input={project_id:form.project_id,mode:form.mode,policy_version:form.policy_version};
  else {if(typeof form.payload!=='string')fail('INVALID_INPUT');try{input=JSON.parse(form.payload);}catch{fail('INVALID_INPUT');}}
  const result=route==='admin'?await review.registry(s.principal,input):await review[route](s.principal,input);
  return reply.type('text/html').send(page('Decision recorded',`<p class="notice">The operation committed successfully.</p><pre>${esc(JSON.stringify(result,null,2))}</pre><p><a href="/">Return to inbox</a> · <a href="/search">Search current knowledge</a></p>`,s.principal.display_name,s.csrf));
 });
 return app;
}
